**1. Importing numpy libraray**

In [4]:
import numpy as np

**2. List vs Numpy Array**

In [6]:
x = [1, 2, 3, 4]
print (x)
type(x)

[1, 2, 3, 4]


list

In [7]:
n = np.array(x)
print(n)
type(n)

[1 2 3 4]


numpy.ndarray

In [15]:
x = [j**3 for j in range(1,9)]
print(x)
%timeit [j**3 for j in range(1,9)]

[1, 8, 27, 64, 125, 216, 343, 512]
1.51 µs ± 15.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
y = np.arange(1,9)**3
print(y)
%timeit np.arange(1,9)**3

[  1   8  27  64 125 216 343 512]
4.29 µs ± 38.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


**3. Taking imput from user for numpy array**

In [18]:
l = []
for i in range(1,5):
    inp = input("Enter : ")
    l.append(inp)
print(l)
print(np.array(l))


Enter : 2
Enter : 5
Enter : 7
Enter : 13
['2', '5', '7', '13']
['2' '5' '7' '13']


**4. Knowing dimensions of array**

In [22]:
n = np.array(l)
print(n)
print(n.ndim)

['2' '5' '7' '13']
1


In [24]:
l2 = [2,4,5,7,8]
l3 = [1,5,8,12,4]
n2 = np.array([l2, l3])
print(l2)
print(l3)
print(n2)

[2, 4, 5, 7, 8]
[1, 5, 8, 12, 4]
[[ 2  4  5  7  8]
 [ 1  5  8 12  4]]


In [26]:
n3 = np.array([[[[[l2, l3]]]]])
print(n3)
print(n3.ndim)

[[[[[[ 2  4  5  7  8]
     [ 1  5  8 12  4]]]]]]
6


In [2]:
#defining dimension of arry exclusively
n4 = np.array([1,2,3,4], ndmin=3)
print(n4)
print(n4.ndim)

[[[1 2 3 4]]]
3


**5. Different types of arrays:**

In [7]:
#1. zeros array
ar_z = np.zeros(3)
print(ar_z)
print()
ar_z2 = np.zeros((3,5))
print(ar_z2)

[0. 0. 0.]

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
#2. ones array
ar_o = np.ones(3)
print(ar_o)
print()
ar_z2 = np.ones((3,5))
print(ar_z2)

[1. 1. 1.]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [18]:
#3. empty array : fill garbage values
ar_e = np.empty(5)
print(ar_e)
print()
ar_e2 = np.empty((4, 2))
print(ar_e2)

[2.12199579e-314 1.30714941e-311 5.19757059e-321 3.79442416e-321
 2.31300682e-312]

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 1.11260755e-306]
 [6.23057688e-307 2.22526399e-307]
 [6.23053614e-307 7.56592338e-307]]


In [29]:
#4. diagonal array:
ar_d = np.eye(3)
print(ar_d)
print()
ar_d2 = np.eye(3,5)
print(ar_d2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [33]:
#5. range
ar_r = np.arange(6)
print(ar_r)
print()
ar_r2 = np.arange(2,6)
print(ar_r2)

[0 1 2 3 4 5]

[2 3 4 5]


In [34]:
#6. linera space array
ar_l = np.linspace(0, 10, num=5)
print(ar_l)

[ 0.   2.5  5.   7.5 10. ]


**6. Creating numpy array with random numbers**

In [36]:
#1. rand
r = np.random.rand(4)
print(r)
print()
r2 = np.random.rand(3,5)
print(r2)

[0.36579511 0.38805625 0.94481262 0.55836327]

[[0.51178252 0.21314163 0.7776999  0.3619273  0.74121313]
 [0.37326493 0.65542409 0.93933629 0.81519845 0.79752649]
 [0.35900735 0.79162615 0.75175925 0.42183926 0.13117693]]


In [38]:
#2. randn -> random number nearest to 0
r = np.random.randn(3)
print(r)
print()
r = np.random.randn(3, 4)
print(r)

[1.55225546 0.08585887 0.3730561 ]

[[ 0.35505947 -1.10361738  1.22493534  1.55667036]
 [-0.39294561  0.35747827 -0.686054    0.32951745]
 [-2.26544891 -0.79433533 -0.2197063   0.46920663]]


In [41]:
#3. ranf ->
r = np.random.ranf(3)
print(r)

[0.78459158 0.76007782 0.93172438]


In [51]:
#4. randint ->
r = np.random.randint(8)
print(r)
print()
r2 = np.random.randint(2, 9)
print(r2)
print()
r3 = np.random.randint(2, 9, 4)
print(r3)

4

7

[7 3 8 5]


**7. Datatypes:**

In [52]:
a = np.array([1,2,3,4])
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [53]:
b = np.array([1.2, 3.5, 6, 8])
print(b)
print(b.dtype)

[1.2 3.5 6.  8. ]
float64


In [54]:
c = np.array(['a', 'z', 's'])
print(c)
print(c.dtype)

['a' 'z' 's']
<U1


In [58]:
d = np.array(('A', "B", 1, 4))
print(d)
print(d.dtype)

['A' 'B' '1' '4']
<U11


In [59]:
e = np.array(('A', "B", 1, 4.4))
print(e)
print(e.dtype)

['A' 'B' '1' '4.4']
<U32


In [73]:
#setting datatype exclusively
a = np.array([1,2,3,4], dtype=np.int32)
print(a)
print(a.dtype)

print()

b = np.array([1,2,3,4], dtype=np.int8)
print(b)
print(b.dtype)

print()

c = np.array([1,2,3,4], dtype="f")
print(c)
print(c.dtype)

print()

d = np.array([1,2,3,4], dtype=np.float64)
print(d)
print(d.dtype)

[1 2 3 4]
int32

[1 2 3 4]
int8

[1. 2. 3. 4.]
float32

[1. 2. 3. 4.]
float64


In [75]:
#converting the datatype by astype()
x = np.array([1,2,3,4])
print(x)
print(x.dtype)

print()

y = x.astype(float)
print(y)
print(y.dtype)

[1 2 3 4]
int32

[1. 2. 3. 4.]
float64


**8. Arithmetic operations: by operator or, by keyword**

In [77]:
a = np.array([1,2,3,4])
b = np.array([2,3,2,3])
print(a+b)
print(np.add(a,b))

[3 5 5 7]
[3 5 5 7]


In [78]:
print(a-b)
print(np.subtract(a,b))

[-1 -1  1  1]
[-1 -1  1  1]


In [79]:
print(a*b)
print(np.multiply(a,b))

[ 2  6  6 12]
[ 2  6  6 12]


In [80]:
print(a/b)
print(np.divide(a,b))

[0.5        0.66666667 1.5        1.33333333]
[0.5        0.66666667 1.5        1.33333333]


In [81]:
print(a**b)
print(np.power(a,b))

[ 1  8  9 64]
[ 1  8  9 64]


In [85]:
print(a%b)
print(np.mod(a,b))

[1 2 1 1]
[1 2 1 1]


In [86]:
print(1/a)
print(np.reciprocal(a))

[1.         0.5        0.33333333 0.25      ]
[1 0 0 0]


In [89]:
a2 = np.array([[1,2,3], [3,2,1]])
b2 = np.array([[1,2,3], [3,2,1]])
print(a2+b2)
print(a2-b2)
print(a2*b2)
print(a2/b2)
print(a2%b2)
print(a2**b2)

[[2 4 6]
 [6 4 2]]
[[0 0 0]
 [0 0 0]]
[[1 4 9]
 [9 4 1]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0 0 0]
 [0 0 0]]
[[ 1  4 27]
 [27  4  1]]


**9. Arithmetic Functions:**

In [94]:
a = np.array([2,3,12,45,67])
print(a)

print(np.max(a))

print(np.min(a))

print(np.argmin(a))

print(np.argmax(a))

print(np.sin(a))

print(np.cos(a))

print(np.cumsum(a))

print(np.sqrt(a))
print(np.sqrt(4))

[ 2  3 12 45 67]
67
2
0
4
[ 0.90929743  0.14112001 -0.53657292  0.85090352 -0.85551998]
[-0.41614684 -0.9899925   0.84385396  0.52532199 -0.5177698 ]
[  2   5  17  62 129]
[1.41421356 1.73205081 3.46410162 6.70820393 8.18535277]
2.0


**10. Broadcasting Numpy arrays:**

**if (size of corresponding dimensions should be same or atleast one of them is 1) -> should be true for all sizes of dimensions from l to r**

In [2]:
n1 = np.array([1,2,3])
print(n1)
n2 = np.array([1,2,3,4])
print(n2)
print()

#gives broadcasting error : as number of elements does not match
print(n1+n2)

[1 2 3]
[1 2 3 4]



ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [4]:
#if 2 arrays are: 1x3 and 3x1 or, 2x1 and 5x2, or, 3x1 and 2x1 , i.e. -> the number second part of multiplication number can be both 1 or atleat one

n1 = np.array([1,2,3])
print(n1)
print(n1.shape)
print()

n2 = np.array([[1],[2],[3]])
print(n2)
print(n2.shape)
print()

print(n1+n2)

[1 2 3]
(3,)

[[1]
 [2]
 [3]]
(3, 1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [21]:
n1 = np.array([[1,2], [2,3]])
print(n1)
print(n1.shape)

print()

n2 = np.array([[1,2], [2,2]])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2]
 [2 3]]
(2, 2)

[[1 2]
 [2 2]]
(2, 2)

[[2 4]
 [4 5]]


In [41]:
n1 = np.array([[1,2,3], [2,3,2]])
print(n1)
print(n1.shape)

print()

n2 = np.array([1,2,3])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2 3]
 [2 3 2]]
(2, 3)

[1 2 3]
(3,)

[[2 4 6]
 [3 5 5]]


In [44]:
n1 = np.array([[1,2,3]])
print(n1)
print(n1.shape)

print()

n2 = np.array([[1,2,3], [2,2,2]])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2 3]]
(1, 3)

[[1 2 3]
 [2 2 2]]
(2, 3)

[[2 4 6]
 [3 4 5]]


In [27]:
n1 = np.array([[1,2,3,4,5], [2,3,2,2,2]])
print(n1)
print(n1.shape)

print()

n2 = np.array([1,2,3,4,5])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2 3 4 5]
 [2 3 2 2 2]]
(2, 5)

[1 2 3 4 5]
(5,)

[[ 2  4  6  8 10]
 [ 3  5  5  6  7]]


In [30]:
n1 = np.array([[1,2], [2,3], [1,2]])
print(n1)
print(n1.shape)

print()

n2 = np.array([1,2])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2]
 [2 3]
 [1 2]]
(3, 2)

[1 2]
(2,)

[[2 4]
 [3 5]
 [2 4]]


In [3]:
n1 = np.array([[1,2]])
print(n1)
print(n1.shape)

print()

n2 = np.array([[1,2],[2,3]])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2]]
(1, 2)

[[1 2]
 [2 3]]
(2, 2)

[[2 4]
 [3 5]]


In [7]:
n1 = np.array([[1,2], [2,4], [5,6]])
print(n1)
print(n1.shape)

print()

n2 = np.array([1,2,3])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2]
 [2 4]
 [5 6]]
(3, 2)

[1 2 3]
(3,)



ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [8]:
n1 = np.array([[1,2], [2,4], [5,6]])
print(n1)
print(n1.shape)

print()

n2 = np.array([1,2])
print(n2)
print(n2.shape)

print()

print(n1+n2)

[[1 2]
 [2 4]
 [5 6]]
(3, 2)

[1 2]
(2,)

[[2 4]
 [3 6]
 [6 8]]


**11. Indexing and slicing**

In [59]:
n1 = np.array([2,4,12,43,11])
print(n1)
print(n1.ndim)
print(n1.shape)

[ 2  4 12 43 11]
1
(5,)


In [63]:
print(n1[2])
print(n1[4])

print()

print(n1[1:3])
print(n1[0:len(n1):2])

12
11

[ 4 12]
[ 2 12 11]


In [64]:
n1 = np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print(n1)
print(n1.ndim)
print(n1.shape)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]
3
(1, 3, 3)


In [68]:
print(n1[0,0,2])
print(n1[0,2,2])

print()

print(n1[0,0,0:2])
print(n1[0,1,0:3])
print(n1[0,2,1:3])

3
5

[1 2]
[2 3 4]
[4 5]


**12. Loop or iterating in nd array**

In [70]:
n1 = np.array([2,4,12,43,11])
print(n1)
print(n1.ndim)
print(n1.shape)

print()

for i in n1:
    print(i)

[ 2  4 12 43 11]
1
(5,)

2
4
12
43
11


In [74]:
n1 = np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print(n1)
print(n1.ndim)
print(n1.shape)

print()

for i in n1:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]
3
(1, 3, 3)

1
2
3
2
3
4
3
4
5


In [77]:
n1 = np.array([[[1,2,3],[2,3,4],[3,4,5]]])
print(n1)
print(n1.ndim)
print(n1.shape)

print()

for i in n1:
    for j in i:
        for k in j:
            print(k)

[[[1 2 3]
  [2 3 4]
  [3 4 5]]]
3
(1, 3, 3)

1
2
3
2
3
4
3
4
5


**note: nditer() -> some confusing to implement as have many parameters**

**13. Copy vs View in numpy array**

**copy() -> owns the data; creates a new array; any change in new array will not reflect in original array**

**view() -> does not owns the data; does not craetes new array, points to original array; any change will reflect in both array**

In [85]:
n1 = np.array([2,5,11,15,23])
print(n1)

print()

n2 = n1.copy()
print(n2)

print()

n3 = n1.view()
print(n3)

[ 2  5 11 15 23]

[ 2  5 11 15 23]

[ 2  5 11 15 23]


In [86]:
n2[3] = 55
print("n1: ", n1)
print("n2: ", n2)

n1:  [ 2  5 11 15 23]
n2:  [ 2  5 11 55 23]


In [87]:
n3[3] = 67
print("n1: ", n1)
print("n3: ", n3)

n1:  [ 2  5 11 67 23]
n3:  [ 2  5 11 67 23]


**14. join numpy arrays**

In [94]:
n1 = np.array([2,5,11,15,23])
print(n1)

n2 = np.concatenate((n1, [55,66,77]))
print(n2)

[ 2  5 11 15 23]
[ 2  5 11 15 23 55 66 77]


In [101]:
#using concatenate()-> to join arrays
n2 = np.array(([1,2,3], [2,3,4]))
print(n2)

print()

n3 = np.array([[2,2,2], [3,3,3]])
print(n3)

print()

n4 = np.concatenate((n2,n3))
print(n4)

print()

n5 = np.concatenate((n2,n3), axis=1)
print(n5)

[[1 2 3]
 [2 3 4]]

[[2 2 2]
 [3 3 3]]

[[1 2 3]
 [2 3 4]
 [2 2 2]
 [3 3 3]]

[[1 2 3 2 2 2]
 [2 3 4 3 3 3]]


In [105]:
#stack() -> to maintain arrays like in stack
n6 = np.stack((n2,n3))
print(n6)

print()

n7 = np.hstack((n2,n3))
print(n7)

print()

n8 = np.vstack((n2,n3))
print(n8)

print()

n9 = np.dstack((n2,n3))
print(n9)

[[[1 2 3]
  [2 3 4]]

 [[2 2 2]
  [3 3 3]]]

[[1 2 3 2 2 2]
 [2 3 4 3 3 3]]

[[1 2 3]
 [2 3 4]
 [2 2 2]
 [3 3 3]]

[[[1 2]
  [2 2]
  [3 2]]

 [[2 3]
  [3 3]
  [4 3]]]


**array_split() -> to split the array**

In [113]:
n1 = np.array([2,3,4,5,6,7,8])
print(n1)
n2 = np.array_split(n1,2)
print(n2)
print(n2[0])
print(type(n2))

[2 3 4 5 6 7 8]
[array([2, 3, 4, 5]), array([6, 7, 8])]
[2 3 4 5]
<class 'list'>


In [115]:
n1 = np.array([[1,2,3], [3,4,5]])
print(n1)
n2 = np.array_split(n1,3)
print(n2)
print(n2[1])

[[1 2 3]
 [3 4 5]]
[array([[1, 2, 3]]), array([[3, 4, 5]]), array([], shape=(0, 3), dtype=int32)]
[[3 4 5]]


**15. numpy array functions**

**where() -> to search the index of elements**

In [122]:
n1 = np.array([[1,2,3], [3,4,5]])
print(n1)

print()

#1st row and 1st column
n2 = np.where(n1 == 4)
print(n2)

#0th row and 0th column
n3 = np.where(n1 == 1)
print(n3)

[[1 2 3]
 [3 4 5]]

(array([1], dtype=int64), array([1], dtype=int64))
(array([0], dtype=int64), array([0], dtype=int64))


In [128]:
n1 = np.array([1,2,3,4,2,1,2,5,6,2,1])
print(n1)

n2 = np.where(n1 == 2)
print(n2)
print()
n3 = np.where(n1%2 == 1)
print(n3)

[1 2 3 4 2 1 2 5 6 2 1]
(array([1, 4, 6, 9], dtype=int64),)

(array([ 0,  2,  5,  7, 10], dtype=int64),)


**searchsorted() -> performs binary search to find the right index to insert the element**

In [133]:
n1 = np.array([1,3,4,6,8])
print(n1)

n2 = np.searchsorted(n1,[5,2])
print(n2)

[1 3 4 6 8]
[3 1]


**sort()**

In [135]:
n1 = np.array(['b', 'a', 'z', 'd', 'h'])
print(n1)

print()

n2 = np.sort(n1)
print(n2)

['b' 'a' 'z' 'd' 'h']

['a' 'b' 'd' 'h' 'z']


In [144]:
#filtering the items
n1 = np.array(['b', 'a', 'z', 'd', 'h'])
print(n1)
n2 = [True, False, False, True, False]
print(n2)

#will apply true/false filter to main array to get only required values
n3 = n1[n2]
print(n3)

['b' 'a' 'z' 'd' 'h']
[True, False, False, True, False]
['b' 'd']


In [ ]:
shuffle(), unique(), flatten(), ravel()

**16. insert(), delete()**

In [154]:
n1 = np.array([2,6,12,45,11])
print(n1)

#index number and the element to insert
n2 = np.insert(n1, 2, 88)
print(n2)

n3 = np.insert(n1, (2,5,1), 51)
print(n3)

n4 = np.insert(n1, (2,5), (9,8))
print(n4)

[ 2  6 12 45 11]
[ 2  6 88 12 45 11]
[ 2 51  6 51 12 45 11 51]
[ 2  6  9 12 45 11  8]


In [153]:
#on basis of index number
n4 = np.delete(n3,4)
print(n4)


[ 2 51  6 51 45 11 51]


In [159]:
n1 = np.array([[1,2,3], [3,4,5]])
print(n1)

n2 = np.insert(n1, (1,1), (55))
print(n2)

n3 = np.insert(n1, (1,1), (55), axis=0)
print(n3)

[[1 2 3]
 [3 4 5]]
[ 1 55 55  2  3  3  4  5]
[[ 1  2  3]
 [55 55 55]
 [55 55 55]
 [ 3  4  5]]


In [ ]:
matrix dtype and matrix vs array, add and mult. in matrix is different-> transpose, swapaxes, power, determinate, inverse, power